DATABASE_URL = "postgresql://postgres.drmfabxyqmtvdjvmtbff:AoutEvy2017*@aws-1-eu-west-1.pooler.supabase.com:6543/postgres"
[users]
admin = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
jenny = "5d96d4f609ba7d1e9c9c89c55c1da0307dfbe7f6bbca6794494528c9e8166497"